spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/mcpractise
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  pattern:
    level: [${spring.application.name},%X{traceId:-},%X{spanId:-}]


